import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import { QueryClientProvider } from "@tanstack/react-query";
import QueryProvider from "./components/QueryProvider";
import { Poppins } from "next/font/google";
import Navbar from "./components/Navbar";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600"],
  display: "swap",
});
// const montserrat =Montserrat({
//   weight:['200','300','400'],
//   subsets:'latin'
// })
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Medicare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-white w-full ${poppins.className}`}>
        <QueryClientProvider client={QueryProvider}>
          <Navbar />
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
